# Generated by Django 4.2.4 on 2023-09-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productsize_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
